
# symbol settings
DEFAULT_SYMBOL = 'BTC'
SUPPORTED_SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'XAUUSDT']

# PIVOT LOOKBACK SETTINGS
LOOKBACK_LEFT = 5
LOOKBACK_RIGHT = 5


# FIB SETTINGS
MIN_RETRACEMENT_FIB = 0.382
MAX_RETRACEMENT_FIB = 0.7


# EMAC CROSS SETTINGS
EMA_PERIODS = (8, 20)


# TIMEFRAME SETTINGS
TRADE_TF_ARGS = ('15m', 100)
HTF_ARGS = ('4h', 1000)

SIGNAL_UPTIME = 4

SL_PADDING = 0.001
TP_RRRS = (2, 5)

# lookback settings
LOOKBACK_VALUES = (5, 5, 5)

